### PR TITLE
Add additional social media icons

### LINKED ISSUE #131: SECONDARY NAVIGATION in the footer
I want to add authors/about pages as SECONDARY NAVIGATION in the footer, can you please suggest me how can i do this?

### PR DESCRIPTION
**Pull request by bernwaldl**
I've added a bunch of social media icons via the [Icomoon](https://icomoon.io/) font generator to be used in the footer when secondary navigation is specified via the Ghost Admin interface in Ghost V3. E.g. if there is an entry in the secondary navigation tab with Label _Instagram_ and URL _http://example.org_, an icon with the Instagram logo that links to _http://example.org_ is shown in the footer of the page.

There are still some problems, that I am currently unable to resolve:

- ~~If an unknown label is specified, no logo is shown in the footer for that item. The space however is still occupied. There should be default logo, such as for example the globe, for unknown labels. I am, however, unsure as to how to check whether a logo exists in Handlebars or whether that even is possible.~~
I've fixed this. However, it has to be ensured that the default social icon always comes before the other social icons in the style. A comment in the code about that has been added.

- ~~When a lot of logos are specified, resizing of the window results in weird behavior: When the window width gets smaller at some point there are more logos on one row than there were when the window width was higher. The CSS `display` properties have to be set correctly. I unfortunately don't know what the right values are.~~
I had to set the `max-width` of the footer content. Although the mentioned property still applies, I have improved the footer to show more icons on bigger screens per row.

### CODE REVIEW

**Comment by eddiesigner** [comment]
I really do appreciate this PR but I can't merge all the changes because when I implement the secondary navigation probably I will do it in a very different way. The changes you've made to the menu and to the footer are probably too specific for your case.

Would you mind to exclude the changes in `footer.hbs`, `navigation.hbs` and `_footer.scss`? 😄 

The icons are quite nice!

**Comment by bernwaldl** [comment]
I understand. I've excluded the changes to the mentioned files. If you don't mind sharing, I'd be interested in your plans implementing the secondary navigation. 😄 

I also had to recheck the licenses of those icons. I made sure to only include icons from the Brands icon pack at IcoMoon. AFAIK they are under [CC 1.0 Universal License](https://github.com/simple-icons/simple-icons/blob/develop/LICENSE.md). Thus their commercial usage should be ok.

Hope the PR is ok to merge now 😄

**Comment by eddiesigner** [comment]
Thanks for the changes!

I'm not quite sure right now 🤔 but I guess I will include a button next to the search button to open the secondary menu or maybe including it somehow inside of the big submenu.

On mobile maybe I will include a button under the main menu to open the secondary menu.

**Comment by bernwaldl** [comment]
Thanks for merging!

Interesting, looking forward to seeing the result 😃

**Comment by darrenmhill** [comment]
Any chance in LinkedIn? And ability to add these to personal profiles?

**Comment by aakashhemadri** [comment]
Is this out in the current release? If so how do I add social links?

**Comment by eddiesigner** [comment]
@darrenmhill The Linkedin icon is already included. I can't add Linkedin to the profile page because is not supported by Ghost at the moment as you can see here: https://ghost.org/docs/api/v3/handlebars-themes/context/author/#author-object-attributes

If you want to use the Linkedin icon somewhere else just use it like this: 
```html
<span class="icon-linkedin"></span>
```

**Comment by eddiesigner** [comment]
@aakashhemadri The latest release already includes those icons so you can use them as you like. If you want to add social links somewhere else you have to do it for yourself.

You can see the list of icons here: https://github.com/eddiesigner/liebling/blob/master/src/sass/common/_icons.scss

Just use them like this:

```html
<!-- Github icon example -->
<span class="icon-github"></span>
```

**Pull request merged**
