### PR TITLE
Add windows develop support

### PR DESCRIPTION
**Pull request by D3473R**
This PR adds Windows develop support.
It just needed a `NODE_ENV` workaround with `win-node-env`.

### CODE REVIEW

**Comment by eddiesigner** [comment]
I will close this and integrate the changes of this one instead: https://github.com/D3473R/liebling/pull/1 because it gives support to Mac OS **and** Windows ;)

**Comment by D3473R** [comment]
Hey, i didn't notice your PR :see_no_evil:
I added `"7zip": "0.0.6"` to the dev dependecies to give cross platform `7z` support. 7zip is not installed as default on windows, so if you are running windows and don't have 7zip installed `7z` would not work.
With this javascript implementation the `7z` command should work on Mac, Linux and Windows. (I sadly can't test in on a Mac, has it not worked for you?)

**Comment by D3473R** [comment]
Windows production build is working with: 44b03beec337d0327edd5c123fa98176d2a69ea8 :thumbsup:

**Comment by eddiesigner** [comment]
Sorry, I forgot to add all the changes 😅 but now everything is there with https://github.com/eddiesigner/liebling/commit/44b03beec337d0327edd5c123fa98176d2a69ea8

I did it that way because on Mac didn't work unless you install 7zip using Homebrew (besides the javascript implementation).

I can't test on Windows but if you say it works just with that module then it's safe to run the task `zip:default` on Mac/Linux and `zip:win32` on Windows 👍

**Pull request closed without merging**
