### PR TITLE
Remove all build assets from git and fix windows build issues

### PR DESCRIPTION
**Pull request by d3473r**
Hi,

i removed and  untracked all `{js|css|font}` files that are build with our CI pipeline anyway.
Also there were some build issues on windows if no python version 2 is installed. (I am now using the build `aos` tarball instead of building it again with our pipeline)
There is also an open [PR](https://github.com/charlesguse/run-script-os/pull/39) in `run-script-os` which fixes another build error.
So for now I switched to the forked repo, we can switch back to the original if the PR gets merged.

Regards,
D3473R

### CODE REVIEW

**Comment by eddiesigner** [comment]
Hey, thanks for this! However I'm afraid that I can't merge it, I got a message some time ago from the Ghost team where they asked me if I could add the build assets to the repo because they got multiple issue reports of people trying to download this repository directly as a zip folder instead of downloading it from the releases page, that's why I put back those files.

Also, I wonder why to use tarball? 🤔

I can see the PR in `run-script-os` is kinda recent so I would prefer to wait until they merge it 😅

**Comment by D3473R** [comment]
Hi, okay I guess its easy for non technical people to think they simply can download the zip and use as is 🤔 

May I propose another solution: 

- We are splitting the `src` directory into a submodule that lives in a seperate repository (e.g. https://github.com/eddiesigner/liebling-src)
- Theme development would take place in this new repository, which will only track source files (as it should be 😉)
- https://github.com/eddiesigner/liebling will be the main repo for the theme as before (llinks to the theme should point here)
- To release a new versions we build a CI pipeline that brings the `src` submodule to the latest commit (`git submodule update --remote --merge`) and copies the build into this repo.

I tested it with the develop branch of my fork https://github.com/D3473R/liebling/tree/develop
Here is the submodule repo https://github.com/D3473R/liebling-src
This should work just fine, some adaption is needed though in the `src` repo (mostly outdated links to the parent folder)
Take a look and tell me what you think 😃 

Regarding the second question: I am getting a build error on windows because i only have python3 installed. I guess the root cause are outdated dependencies in https://github.com/eddiesigner/aos notably `node-gyp`: `npm ERR! npm ERR! gyp ERR! stack Error: Command failed: C:\Python39\python3.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];`.
The tarball solution works around this issue as no build of `aos` is necessary. The tarball already contains the build sources, this also speeds of our build time.

To the last point, yeah we can wait until it gets merged, i can switch locally to the fork until it is fixed.

**Comment by eddiesigner** [comment]
Hi 👋 
I think that's a very good idea, I like it. Probably I will need to mention somewhere that if someone wants to contribute by changing something in the source files, they should do it in the other repository and probably I will need to modify some entries in the Wiki as well.

Btw, something would change in the [theme development process](https://github.com/eddiesigner/liebling/wiki/Theme-development-with-Docker)?

I saw that the PR in the `run-script-o` repository is already merged, I would like to integrate those changes with this PR so I kindly ask you if you can remove all the changes in the assets files and just leave the ones related to the dependencies :)

**Comment by d3473r** [comment]
Hi again, i'm finally having more free time right now. 
The docs for the theme development process then have to move to the new repo.
Can you create the new repo [https://github.com/eddiesigner/liebling-src](https://github.com/eddiesigner/liebling-src)?
Then I will open a PR there with the current src directory's git tree.
Regards

**Comment by eddiesigner** [comment]
Hi 👋🏻

Sorry for the late response 😅, I already created the new repo: https://github.com/eddiesigner/liebling-src

You can now open a PR whenever you prefer, thank you again!

Cheers.

**Comment by d3473r** [comment]
Perfect :+1: . I think you have to create a file in the repo then i am able to fork it.
You can create the license file or the the readme :)

**Comment by eddiesigner** [comment]
Done! I didn't know that I had to create a file first 😅

**Comment by d3473r** [comment]
I didn't know i either :D

**Comment by eddiesigner** [comment]
So I already added the [src](https://github.com/eddiesigner/liebling-src) submodule in the [develop](https://github.com/eddiesigner/liebling/tree/develop) branch but I'm a bit lost regarding the CI pipeline, how or where it should be configured? 😅 It has something to do with Github actions?

**Pull request closed without merging**
